CREATE TABLE IF NOT EXISTS `mydb`.`CUSTOMERS_F` (
  `CUSTOMER_ID` INT NOT NULL,
  `LASTNAME` VARCHAR(100) NULL,
  `FIRSTNAME` VARCHAR(100) NULL,
  `MIDDLENAME` VARCHAR(100) NULL,
  `STREET` VARCHAR(100) NULL,
  `CITY` VARCHAR(100) NULL,
  `STATE` VARCHAR(100) NULL,
  `COUNTRY` VARCHAR(100) NULL,
  `ZIPCODE` INT NULL,
  `OCCUPATION` VARCHAR(100) NULL,
  `REPEATCUSTOMER` TINYINT(1) NULL,
  `NOTES` VARCHAR(100) NULL,
  `TRANSACTIONS_TRANSACTIONS` INT NOT NULL,
  `LEGEND_ID` VARCHAR(45) NOT NULL,
  `CUSTOMERS_F_CUSTOMER_ID` INT NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  INDEX `fk_CUSTOMERS_F_TRANSACTIONS1_idx` (`TRANSACTIONS_TRANSACTIONS` ASC),
  INDEX `fk_CUSTOMERS_F_LEGEND1_idx` (`LEGEND_ID` ASC),
  INDEX `fk_CUSTOMERS_F_CUSTOMERS_F1_idx` (`CUSTOMERS_F_CUSTOMER_ID` ASC),
  CONSTRAINT `fk_CUSTOMERS_F_TRANSACTIONS1`
    FOREIGN KEY (`TRANSACTIONS_TRANSACTIONS`)
    REFERENCES `mydb`.`TRANSACTIONS` (`TRANSACTIONS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMERS_F_LEGEND1`
    FOREIGN KEY (`LEGEND_ID`)
    REFERENCES `mydb`.`LEGEND` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMERS_F_CUSTOMERS_F1`
    FOREIGN KEY (`CUSTOMERS_F_CUSTOMER_ID`)
    REFERENCES `mydb`.`CUSTOMERS_F` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB