CREATE TABLE IF NOT EXISTS `mydb`.`File_A_Inventory` (
  `ID` INT NOT NULL,
  `VIN` VARCHAR(100) NOT NULL,
  `YEAR` INT NULL,
  `MANUFACTURER` VARCHAR(100) NULL,
  `MODEL` VARCHAR(100) NULL,
  `WHEELDRIVE` VARCHAR(100) NULL,
  `COLOR` VARCHAR(100) NULL,
  `DOORS` INT NULL,
  `ENGINETYPE` VARCHAR(100) NULL,
  `MSRP` DECIMAL NULL,
  `CID` VARCHAR(100) NULL,
  `SID` VARCHAR(100) NULL,
  `FILE_C_CUSTOMER_RELATIONS_CID` VARCHAR(100) NOT NULL,
  `LEGEND_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VIN`),
  INDEX `fk_File_A_Inventory_LEGEND1_idx` (`LEGEND_ID` ASC),
  CONSTRAINT `fk_File_A_Inventory_LEGEND1`
    FOREIGN KEY (`LEGEND_ID`)
    REFERENCES `mydb`.`LEGEND` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB