CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACTIONS` (
  `TRANSACTIONS` INT NOT NULL,
  `ASSOCIATE_NAME` VARCHAR(45) NULL,
  `BUY` TINYINT NULL,
  `TRADE` VARCHAR(45) NULL,
  `SALE` VARCHAR(45) NULL,
  `BUY_PRICE` VARCHAR(45) NULL,
  `TRADE_VALUE` VARCHAR(45) NULL,
  `STICKER` VARCHAR(45) NULL,
  `SALE_PRICE` VARCHAR(45) NULL,
  `DATE` DATETIME NULL,
  `BUY_VIN` VARCHAR(100) NULL,
  `SALE_VIN` VARCHAR(100) NULL,
  `NOTES` VARCHAR(500) NULL,
  `SALEDATE` VARCHAR(45) NULL,
  `DISCOUNT` VARCHAR(45) NULL,
  `PURCHASEPRICE` VARCHAR(45) NULL,
  `CUSTOMERS_TRANSACTIONS` INT NOT NULL,
  `LEGEND_ID` VARCHAR(45) NOT NULL,
  `CUSTOMERS_F_CUSTOMER_ID` INT NOT NULL,
  `File_A_Inventory_VIN` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TRANSACTIONS`),
  INDEX `fk_TRANSACTIONS_LEGEND1_idx` (`LEGEND_ID` ASC),
  INDEX `fk_TRANSACTIONS_CUSTOMERS_F1_idx` (`CUSTOMERS_F_CUSTOMER_ID` ASC),
  INDEX `fk_TRANSACTIONS_File_A_Inventory1_idx` (`File_A_Inventory_VIN` ASC),
  CONSTRAINT `fk_TRANSACTIONS_LEGEND1`
    FOREIGN KEY (`LEGEND_ID`)
    REFERENCES `mydb`.`LEGEND` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTIONS_CUSTOMERS_F1`
    FOREIGN KEY (`CUSTOMERS_F_CUSTOMER_ID`)
    REFERENCES `mydb`.`CUSTOMERS_F` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTIONS_File_A_Inventory1`
    FOREIGN KEY (`File_A_Inventory_VIN`)
    REFERENCES `mydb`.`File_A_Inventory` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB